# Site settings
title: Marco Bunge
header-img: img/default.jpg
email: mjls@web.de
description: "Blogging about Software, Frameworks and Workflows. Code documentation of Furnace"
baseurl: ""
url: "http://marco-bunde.de"
twitter_username: makk_eightbit
github_username:  mbunge
facebook_username:  marco.bunge.dev

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","_drafts"]
